### ISSUE TITLE
Helping with the project

### ISSUE THREAD

**Issue by kheera** [cuonic/PHPAuth#1]
Yeah, I'd love to help with this.

I've just setup my editor to enforce PSR2 style guide.

Are you using any coding standards or style guides that I should adopt or would you be interested in adopting PSR2?

What should I work on first?

Shane

**Comment by kheera** [comment]
Ok great.

I created a new branch with the PSR2 changes. 

Do you have any work in progress? I'm not sure if we'll get a bunch of merge conflicts here so maybe try merging this into your work in progress? If there's problems it's OK, we can dump this branch. I found a utility which auto converts into PSR2 so we can just do that again with your most current work.

If there's nothing in progress, or no conflicts, I can merge this into master.

Regarding line endings... PSR2 states all PHP files must use LF line endings. I'm not sure if that worked here or not.

**Comment by cuonic** [comment]
No work in progress here so you can go ahead and merge.

**Comment by kheera** [comment]
Done.
