### ISSUE TITLE
FAQs about the script

### ISSUE THREAD

**Issue by SherazAhmed93** [cuonic/PHPAuth#13]
I read that [this repo](https://github.com/cuonic/PHPAuth) is the OOP based version of the [this](https://github.com/PHPAuth/PHPAuth) script, do you would it work on php 5.6 and how much is it completed?

**Comment by cuonic** [comment]
The previous PHPAuth was also OOP based, but when I first started I didn't really understand all the concepts clearly. This new version is better in terms of OOP concepts. This only works on PHP 7.0 and up.
